### ISSUE TITLE
Language 

### ISSUE THREAD

**Issue by jlaurencin** [nkasmanoff/pi-card#8]
I think it's work in English.
Are you thinking of implementing other languages such as Spanish, French, Italian or German ?

**Comment by nkasmanoff** [comment]
@jlaurencin So far, just works in english.

If we were to change the transcription model to multi-lingual that would be a quick fix, and I think with https://huggingface.co/CohereForAI/aya-23-8B makes other languages more possible too. I may set up a new branch which can test this. 

One problem I think will happen is the text to voice service used here, espeak, probably won't hold up very well in other languages, so that will need to be updated to on top of the models, and I'm not sure what to use that can be used on device. Do you have any suggestions for text to speech tools that can work in these languages?
